FROM golang:1.25.8-alpine AS builder

WORKDIR /app

RUN apk add --no-cache git

COPY go.mod go.sum ./
RUN go mod download

COPY . .

RUN CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -o migrator ./cmd/migrator

FROM alpine:3.20

WORKDIR /app

COPY --from=builder /app/migrator .
COPY --from=builder /app/internal/infrastructure/postgres/migrations ./migrations

ENV MIGRATIONS_PATH=/app/migrations

CMD ["./migrator"]