// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	jwt "github.com/leyl1ne/UserService/internal/infrastructure/auth/jwt"
	mock "github.com/stretchr/testify/mock"
)

// AccessTokenProvider is an autogenerated mock type for the AccessTokenProvider type
type AccessTokenProvider struct {
	mock.Mock
}

// GenerateAccessToken provides a mock function with given fields: payload
func (_m *AccessTokenProvider) GenerateAccessToken(payload jwt.Payload) (string, error) {
	ret := _m.Called(payload)

	if len(ret) == 0 {
		panic("no return value specified for GenerateAccessToken")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(jwt.Payload) (string, error)); ok {
		return rf(payload)
	}
	if rf, ok := ret.Get(0).(func(jwt.Payload) string); ok {
		r0 = rf(payload)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(jwt.Payload) error); ok {
		r1 = rf(payload)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewAccessTokenProvider creates a new instance of AccessTokenProvider. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewAccessTokenProvider(t interface {
	mock.TestingT
	Cleanup(func())
}) *AccessTokenProvider {
	mock := &AccessTokenProvider{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
